# Generated by Django 5.0.3 on 2024-03-14 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deatails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact_deatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenum', models.IntegerField()),
                ('emailid', models.EmailField(max_length=200, null=True)),
                ('accno', models.BigIntegerField()),
                ('status', models.SmallIntegerField(default=1)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_code', models.CharField(max_length=100)),
                ('vendor_gst', models.CharField(max_length=200)),
                ('vendor_branch', models.CharField(max_length=200)),
                ('vendor_pan', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_deatails.address')),
                ('contact_deatails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_deatails.contact_deatails')),
            ],
        ),
    ]
