# Generated by Django 5.0.3 on 2024-03-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deatails', '0002_address_contact_deatails_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_deatails',
            name='mobilenum',
            field=models.BigIntegerField(),
        ),
    ]
