# Generated by Django 5.0.3 on 2024-03-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_deatails', '0003_alter_contact_deatails_mobilenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='address',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='contact_deatails',
            new_name='contact_deatails_id',
        ),
    ]
